global using AutoMapper;
global using Domain.Enums;
global using Domain.Exceptions;
global using Domain.Interfaces.DataProviders;
global using Domain.Interfaces.Dtos;
global using Domain.Setting;
global using FluentValidation;
global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;